# Generated by Django 2.1.1 on 2018-09-12 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newspiece',
            name='news_abstract',
            field=models.CharField(default='default', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tag',
            name='newspiece',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.NewsPiece'),
        ),
    ]
